# Quick demonstration configuration
simulation:
  duration: 40.0  # 40 seconds to see all events
  real_time_factor: 0.01  # Very fast for demo
  inject_faults: true
  output_dir: "./logs"

devices:
  - device:
      name: "R1"
      type: "router"
    interfaces:
      - name: "eth0"
        ip_address: "192.168.1.1"
        subnet_mask: "255.255.255.0"
        status: "up"
      - name: "eth1"
        ip_address: "10.0.0.1" 
        subnet_mask: "255.255.255.0"
        status: "up"
        
  - device:
      name: "R2" 
      type: "router"
    interfaces:
      - name: "eth0"
        ip_address: "10.0.0.2"
        subnet_mask: "255.255.255.0"
        status: "up"
      - name: "eth1"
        ip_address: "192.168.2.1"
        subnet_mask: "255.255.255.0"
        status: "up"

links:
  - id: "r1_r2"
    source: "R1"
    target: "R2"
    properties:
      bandwidth: "100Mbps"

# Demonstrate all fault types
fault_scenarios:
  - name: "Quick_Link_Failure"
    type: "link_failure"
    target: "r1_r2"
    start_time: 5.0
    duration: 10.0
    description: "Test link failure and recovery"
    
  - name: "MTU_Mismatch_Demo"
    type: "mtu_mismatch"
    source: "R1"
    target: "R2"
    packet_size: 1600
    interface_mtu: 1500
    start_time: 20.0
    description: "Demonstrate MTU mismatch handling"
    
  - name: "Interface_Shutdown"
    type: "config_change"
    target: "R2"
    start_time: 30.0
    changes:
      interface_status:
        interface: "eth1"
        status: "down"
    description: "Shutdown an interface during simulation"